[build]
  # Build command - client only for static hosting
  command = "vite build"
  
  # Directory where the build files are located
  publish = "dist/public"
  
  # Node.js version - updated to 20 for @octokit compatibility
  environment = { NODE_VERSION = "20" }

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"